@hostname = localhost
@port = 4000
@host = {{hostname}}:{{port}}
@id = 6
@basePath = api/foro

@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjo3LCJlbWFpbCI6ImVkdWNhZG9yQGNvcnJlby5jb20iLCJ1c2VyX3R5cGUiOiJlZHVjYWRvciIsImlhdCI6MTcxNjAzMDE3MywiZXhwIjoxNzE2MDMzNzczfQ.OQQMTP1TQVUCC7PS9aAMZ6NjJh874-ZP703qM6v6Cfc

### List Foros
GET http://{{host}}/{{basePath}} HTTP/1.1
content-type: application/json
Authorization: Bearer {{token}}
### Get Foro by Id
GET http://{{host}}/{{basePath}}/{{id}} HTTP/1.1
content-type: application/json
Authorization: Bearer {{token}}

### Create Foro
POST http://{{host}}/{{basePath}} HTTP/1.1
content-type: application/json
Authorization: Bearer {{token}}

{
    "titulo_foro": "Foro Preguntas y Respuestas",
    "descripcion_foro": "Foro para plantear preguntas y respuestas sobre la aplicación",
}


### Update Foro
PUT http://{{host}}/{{basePath}}/{{id}} HTTP/1.1
content-type: application/json
Authorization: Bearer {{token}}

{

}

### Delete Foro
DELETE http://{{host}}/{{basePath}}/{{id}} HTTP/1.1
content-type: application/json
Authorization: Bearer {{token}}
