@hostname = localhost
@port = 4000
@host = {{hostname}}:{{port}}
@id = 53
@basePath = api/usuarios

@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjo2MCwiZW1haWwiOiJkaXJlY3RvckBjb3JyZW8uY29tIiwidXNlcl90eXBlIjoiZGlyZWN0b3IiLCJ1c2VyX2Z1bGxuYW1lIjoiQW5nZWwgTmF2YXJybyIsImlhdCI6MTcxNzA3Mjc5MiwiZXhwIjoxNzE3MDc5OTkyfQ.Zc3tCFymotJllIbxeL-vXsu7sTEucKmL61bx93WIUjY

### List Users
GET http://{{host}}/{{basePath}} HTTP/1.1
content-type: application/json
Authorization: Bearer {{token}}

### Get User by Id
GET http://{{host}}/{{basePath}}/{{id}} HTTP/1.1
content-type: application/json
Authorization: Bearer {{token}}

### Create User
POST http://{{host}}/{{basePath}} HTTP/1.1
content-type: application/json
Authorization: Bearer {{token}}

{
    "nombre_usuario": "Xokas",
    "apellido_usuario": "Sorolla",
    "email": "estudiante2000@correo.com",
    "contrasena": "Gracia1122",
    "tipo_usuario": "estudiante",
    "escuela_id": 1,
    "foto_usuario": null
}

### Update User
PUT http://{{host}}/{{basePath}}/{{id}} HTTP/1.1
content-type: application/json
Authorization: Bearer {{token}}

{
    "nombre_usuario": "Pedrito",
    "apellido_usuario": "Gonzalez",
    "email": "pgzl@correo.com",
    "contrasena": "Gracia1122",
    "tipo_usuario": "estudiante",
    "escuela_id": 1,
    "foto_usuario": null
}

### Delete User
DELETE http://{{host}}/{{basePath}}/{{id}} HTTP/1.1
content-type: application/json
Authorization: Bearer {{token}}
