@hostname = localhost
@port = 4000
@host = {{hostname}}:{{port}}
@id = 6
@basePath = api/usuarios

@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjo3LCJlbWFpbCI6ImVkdWNhZG9yQGNvcnJlby5jb20iLCJ1c2VyX3R5cGUiOiJlZHVjYWRvciIsImlhdCI6MTcxMjI4MjU4NSwiZXhwIjoxNzEyMjg2MTg1fQ.1n62CTEOoed11Vwm7PLFEVYeP2yuYQWFu3bJU3E7_VE

### List Users
GET http://{{host}}/{{basePath}} HTTP/1.1
content-type: application/json
Authorization: Bearer {{token}}
### Get User by Id
GET http://{{host}}/{{basePath}}/{{id}} HTTP/1.1
content-type: application/json
Authorization: Bearer {{token}}

### Create User
POST http://{{host}}/{{basePath}} HTTP/1.1
content-type: application/json
Authorization: Bearer {{token}}

{
    "nombre_usuario": "gregorio",
    "apellido_usuario": "araque",
    "email": "educador@correo.com",
    "contrasena": "1234",
    "tipo_usuario": "educador",
    "escuela_id": 1,
    "foto_usuario": null
}


### Update User
PUT http://{{host}}/{{basePath}}/{{id}} HTTP/1.1
content-type: application/json
Authorization: Bearer {{token}}

{
    "nombre_usuario": "kevin",
    "apellido_usuario": "alvarez",
    "email": "estudiante2@correo.com",
    "contrasena": "123456",
    "tipo_usuario": "estudiante",
    "escuela_id": 1,
    "foto_usuario": ""
}

### Delete User
DELETE http://{{host}}/{{basePath}}/{{id}} HTTP/1.1
content-type: application/json
Authorization: Bearer {{token}}
