@hostname = localhost
@port = 4000
@host = {{hostname}}:{{port}}
@id = 6
@basePath = api/usuarios

### List Users
GET http://{{host}}/{{basePath}} HTTP/1.1
content-type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjcsImVtYWlsIjoiZWR1Y2Fkb3JAY29ycmVvLmNvbSIsImlhdCI6MTcwODM3NDU1NCwiZXhwIjoxNzA4Mzc4MTU0fQ.KupnlkQ-rEDexWeKKstG_ppJeYuSu3s7eNYEMu6jkfQ

### Get User by Id
GET http://{{host}}/{{basePath}}/{{id}} HTTP/1.1
content-type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjcsImVtYWlsIjoiZWR1Y2Fkb3JAY29ycmVvLmNvbSIsImlhdCI6MTcwODI4MTkyNCwiZXhwIjoxNzA4Mjg1NTI0fQ.ujDw9NHpQlEJa4r9UCgF8uiRdoI9Wrg3M-Nke7et9uA

### Create User
POST http://{{host}}/{{basePath}} HTTP/1.1
content-type: application/json

{
    "nombre_usuario": "gregorio",
    "apellido_usuario": "araque",
    "email": "educador@correo.com",
    "contrasena": "1234",
    "tipo_usuario": "educador",
    "escuela_id": 1,
    "foto_usuario": null
}


### Update User
PUT http://{{host}}/{{basePath}}/{{id}} HTTP/1.1
content-type: application/json

{
    "nombre_usuario": "kevin",
    "apellido_usuario": "alvarez",
    "email": "estudiante2@correo.com",
    "contrasena": "123456",
    "tipo_usuario": "estudiante",
    "escuela_id": 1,
    "foto_usuario": ""
}

### Delete User
DELETE http://{{host}}/{{basePath}}/{{id}} HTTP/1.1
content-type: application/json
